#!/bin/bash

# Format all hand-written C++ sources under src/ and test/.  *.tab.{cpp,hpp}
# are generated by bison and must not be reformatted -- clang-format is not
# idempotent on them.  test/fixtures/ holds model files (and any stray sources
# among them are fixtures, not hand-written code), so it is excluded too.
#
# Use find's -not -name / -not -path predicates instead of grep to exclude the
# generated and fixture files: BSD grep (default on macOS) treats \| as a
# literal pipe character in BRE, not as alternation, so a grep filter silently
# fails there.  -path with a leading '*' matches under either search root and
# stays portable across BSD and GNU find.
find src test \( -name '*.cpp' -o -name '*.h' -o -name '*.hpp' \) \
    -not -name '*.tab.cpp' -not -name '*.tab.hpp' \
    -not -path '*/fixtures/*' \
    -print0 | xargs -0 clang-format -i
